### PR TITLE
Highlight telomeres and chr discrepancies

### PR DESCRIPTION
**Pull request by pgonzale60**
Hi Samuel,

I liked a lot your work with plotting butterfly chromosomes. Lately I have been focusing on telomeres and wanted to add the feature of displaying whether a sequence has telomere in the plot that also shows potential fusions. 

Best wishes,
Pablo

### CODE REVIEW

**Comment by pgonzale60** [comment]
I also added an MIT license. Without a license, no one is legally allowed to modify, copy or redistribute your code. Please feel free to add your name if you agree with the license or let's discuss about it.

**Comment by Ivypillar** [comment]
Hi Pablo, thanks for contributing! Adding telomeres to the plot is a cool idea. Are you planning to look for telomere sequences around the locations of suspected fusion events or something like this? Also, thanks for the suggestion regarding the licence, it's not something I would have thought of.

**Comment by Ivypillar** [comment]
I've added some bits to your parse_fasta function that hopefully gives you the behaviour you want (adding a "cap" when a telomeric repeat units >minTeloOccur is found around the start or end of a sequence)

**Comment by pgonzale60** [comment]
I'm looking into chromosome diminution in nematodes and this brought me to care about whether the sequences are "complete", meaning they are telomere to telomere. This feature is mostly useful for curating the assemblies rather than to interpret an already chromosomally complete assembly.
Also I notice the bits you added make a clear improvement in detecting telomeres in the Pieris example. Thank you!

**Pull request merged**
